{{- if and .Values.externalSecret.enabled .Values.externalSecret.createSecretStore }}
apiVersion: {{ .Values.externalSecret.secretStoreApiVersion | default "external-secrets.io/v1" }}
kind: {{ default "ClusterSecretStore" .Values.externalSecret.secretStoreRef.kind }}
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name | lower }}
  {{- if ne (default "ClusterSecretStore" .Values.externalSecret.secretStoreRef.kind) "ClusterSecretStore" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region | default "eu-west-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "NeonSecurityTask-chart.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}

